export const COUNTRIES = [
    { code: 'AF', flag: '🇦🇫', dial: '+93', name: 'Afghanistan' },
    { code: 'AL', flag: '🇦🇱', dial: '+355', name: 'Albania' },
    { code: 'DZ', flag: '🇩🇿', dial: '+213', name: 'Algeria' },
    { code: 'AD', flag: '🇦🇩', dial: '+376', name: 'Andorra' },
    { code: 'AO', flag: '🇦🇴', dial: '+244', name: 'Angola' },
    { code: 'AR', flag: '🇦🇷', dial: '+54', name: 'Argentina' },
    { code: 'AM', flag: '🇦🇲', dial: '+374', name: 'Armenia' },
    { code: 'AU', flag: '🇦🇺', dial: '+61', name: 'Australia' },
    { code: 'AT', flag: '🇦🇹', dial: '+43', name: 'Austria' },
    { code: 'AZ', flag: '🇦🇿', dial: '+994', name: 'Azerbaijan' },
    { code: 'BH', flag: '🇧🇭', dial: '+973', name: 'Bahrain' },
    { code: 'BD', flag: '🇧🇩', dial: '+880', name: 'Bangladesh' },
    { code: 'BY', flag: '🇧🇾', dial: '+375', name: 'Belarus' },
    { code: 'BE', flag: '🇧🇪', dial: '+32', name: 'Belgium' },
    { code: 'BZ', flag: '🇧🇿', dial: '+501', name: 'Belize' },
    { code: 'BJ', flag: '🇧🇯', dial: '+229', name: 'Benin' },
    { code: 'BT', flag: '🇧🇹', dial: '+975', name: 'Bhutan' },
    { code: 'BO', flag: '🇧🇴', dial: '+591', name: 'Bolivia' },
    { code: 'BA', flag: '🇧🇦', dial: '+387', name: 'Bosnia and Herzegovina' },
    { code: 'BW', flag: '🇧🇼', dial: '+267', name: 'Botswana' },
    { code: 'BR', flag: '🇧🇧', dial: '+55', name: 'Brazil' },
    { code: 'BN', flag: '🇧🇳', dial: '+673', name: 'Brunei' },
    { code: 'BG', flag: '🇧🇬', dial: '+359', name: 'Bulgaria' },
    { code: 'BF', flag: '🇧🇫', dial: '+226', name: 'Burkina Faso' },
    { code: 'BI', flag: '🇧🇮', dial: '+257', name: 'Burundi' },
    { code: 'KH', flag: '🇰🇭', dial: '+855', name: 'Cambodia' },
    { code: 'CM', flag: '🇨🇲', dial: '+237', name: 'Cameroon' },
    { code: 'CA', flag: '🇨🇦', dial: '+1', name: 'Canada' },
    { code: 'CV', flag: '🇨🇻', dial: '+238', name: 'Cape Verde' },
    { code: 'CF', flag: '🇨🇫', dial: '+236', name: 'Central African Republic' },
    { code: 'TD', flag: '🇹🇩', dial: '+235', name: 'Chad' },
    { code: 'CL', flag: '🇨🇱', dial: '+56', name: 'Chile' },
    { code: 'CN', flag: '🇨🇳', dial: '+86', name: 'China' },
    { code: 'CO', flag: '🇨🇴', dial: '+57', name: 'Colombia' },
    { code: 'KM', flag: '🇰🇲', dial: '+269', name: 'Comoros' },
    { code: 'CG', flag: '🇨🇬', dial: '+242', name: 'Congo' },
    { code: 'CR', flag: '🇨🇷', dial: '+506', name: 'Costa Rica' },
    { code: 'HR', flag: '🇭🇷', dial: '+385', name: 'Croatia' },
    { code: 'CU', flag: '🇨🇺', dial: '+53', name: 'Cuba' },
    { code: 'CY', flag: '🇨🇾', dial: '+357', name: 'Cyprus' },
    { code: 'CZ', flag: '🇨🇿', dial: '+420', name: 'Czech Republic' },
    { code: 'DK', flag: '🇩🇰', dial: '+45', name: 'Denmark' },
    { code: 'DJ', flag: '🇩🇯', dial: '+253', name: 'Djibouti' },
    { code: 'EC', flag: '🇪🇨', dial: '+593', name: 'Ecuador' },
    { code: 'EG', flag: '🇪🇬', dial: '+20', name: 'Egypt' },
    { code: 'SV', flag: '🇸🇻', dial: '+503', name: 'El Salvador' },
    { code: 'GQ', flag: '🇬🇶', dial: '+240', name: 'Equatorial Guinea' },
    { code: 'ER', flag: '🇪🇷', dial: '+291', name: 'Eritrea' },
    { code: 'EE', flag: '🇪🇪', dial: '+372', name: 'Estonia' },
    { code: 'ET', flag: '🇪🇹', dial: '+251', name: 'Ethiopia' },
    { code: 'FJ', flag: '🇫🇯', dial: '+679', name: 'Fiji' },
    { code: 'FI', flag: '🇫🇮', dial: '+358', name: 'Finland' },
    { code: 'FR', flag: '🇫🇷', dial: '+33', name: 'France' },
    { code: 'GA', flag: '🇬🇦', dial: '+241', name: 'Gabon' },
    { code: 'GM', flag: '🇬🇲', dial: '+220', name: 'Gambia' },
    { code: 'GE', flag: '🇬🇪', dial: '+995', name: 'Georgia' },
    { code: 'DE', flag: '🇩🇪', dial: '+49', name: 'Germany' },
    { code: 'GH', flag: '🇬🇭', dial: '+233', name: 'Ghana' },
    { code: 'GR', flag: '🇬🇷', dial: '+30', name: 'Greece' },
    { code: 'GT', flag: '🇬🇹', dial: '+502', name: 'Guatemala' },
    { code: 'GN', flag: '🇬🇳', dial: '+224', name: 'Guinea' },
    { code: 'GY', flag: '🇬🇾', dial: '+592', name: 'Guyana' },
    { code: 'HT', flag: '🇭🇹', dial: '+509', name: 'Haiti' },
    { code: 'HN', flag: '🇭🇳', dial: '+504', name: 'Honduras' },
    { code: 'HU', flag: '🇭🇺', dial: '+36', name: 'Hungary' },
    { code: 'IS', flag: '🇮🇸', dial: '+354', name: 'Iceland' },
    { code: 'IN', flag: '🇮🇳', dial: '+91', name: 'India' },
    { code: 'ID', flag: '🇮🇩', dial: '+62', name: 'Indonesia' },
    { code: 'IR', flag: '🇮🇷', dial: '+98', name: 'Iran' },
    { code: 'IQ', flag: '🇮🇶', dial: '+964', name: 'Iraq' },
    { code: 'IE', flag: '🇮🇪', dial: '+353', name: 'Ireland' },
    { code: 'IL', flag: '🇮🇱', dial: '+972', name: 'Israel' },
    { code: 'IT', flag: '🇮🇹', dial: '+39', name: 'Italy' },
    { code: 'JM', flag: '🇯🇲', dial: '+1-876', name: 'Jamaica' },
    { code: 'JP', flag: '🇯🇵', dial: '+81', name: 'Japan' },
    { code: 'JO', flag: '🇯🇴', dial: '+962', name: 'Jordan' },
    { code: 'KZ', flag: '🇰🇿', dial: '+7', name: 'Kazakhstan' },
    { code: 'KE', flag: '🇰🇪', dial: '+254', name: 'Kenya' },
    { code: 'KW', flag: '🇰🇼', dial: '+965', name: 'Kuwait' },
    { code: 'KG', flag: '🇰🇬', dial: '+996', name: 'Kyrgyzstan' },
    { code: 'LA', flag: '🇱🇦', dial: '+856', name: 'Laos' },
    { code: 'LV', flag: '🇱🇻', dial: '+371', name: 'Latvia' },
    { code: 'LB', flag: '🇱🇧', dial: '+961', name: 'Lebanon' },
    { code: 'LS', flag: '🇱🇸', dial: '+266', name: 'Lesotho' },
    { code: 'LR', flag: '🇱🇷', dial: '+231', name: 'Liberia' },
    { code: 'LY', flag: '🇱🇾', dial: '+218', name: 'Libya' },
    { code: 'LI', flag: '🇱🇮', dial: '+423', name: 'Liechtenstein' },
    { code: 'LT', flag: '🇱🇹', dial: '+370', name: 'Lithuania' },
    { code: 'LU', flag: '🇱🇺', dial: '+352', name: 'Luxembourg' },
    { code: 'MG', flag: '🇲🇬', dial: '+261', name: 'Madagascar' },
    { code: 'MW', flag: '🇲🇼', dial: '+265', name: 'Malawi' },
    { code: 'MY', flag: '🇲🇾', dial: '+60', name: 'Malaysia' },
    { code: 'MV', flag: '🇲🇻', dial: '+960', name: 'Maldives' },
    { code: 'ML', flag: '🇲🇱', dial: '+223', name: 'Mali' },
    { code: 'MT', flag: '🇲🇹', dial: '+356', name: 'Malta' },
    { code: 'MR', flag: '🇲🇷', dial: '+222', name: 'Mauritania' },
    { code: 'MU', flag: '🇲🇺', dial: '+230', name: 'Mauritius' },
    { code: 'MX', flag: '🇲🇽', dial: '+52', name: 'Mexico' },
    { code: 'MC', flag: '🇲🇨', dial: '+377', name: 'Monaco' },
    { code: 'MN', flag: '🇲🇳', dial: '+976', name: 'Mongolia' },
    { code: 'ME', flag: '🇲🇪', dial: '+382', name: 'Montenegro' },
    { code: 'MA', flag: '🇲🇦', dial: '+212', name: 'Morocco' },
    { code: 'MZ', flag: '🇲🇿', dial: '+258', name: 'Mozambique' },
    { code: 'MM', flag: '🇲🇲', dial: '+95', name: 'Myanmar' },
    { code: 'NA', flag: '🇳🇦', dial: '+264', name: 'Namibia' },
    { code: 'NP', flag: '🇳🇵', dial: '+977', name: 'Nepal' },
    { code: 'NL', flag: '🇳🇱', dial: '+31', name: 'Netherlands' },
    { code: 'NZ', flag: '🇳🇿', dial: '+64', name: 'New Zealand' },
    { code: 'NI', flag: '🇳🇮', dial: '+505', name: 'Nicaragua' },
    { code: 'NE', flag: '🇳🇪', dial: '+227', name: 'Niger' },
    { code: 'NG', flag: '🇳🇬', dial: '+234', name: 'Nigeria' },
    { code: 'KP', flag: '🇰🇵', dial: '+850', name: 'North Korea' },
    { code: 'MK', flag: '🇲🇰', dial: '+389', name: 'North Macedonia' },
    { code: 'NO', flag: '🇳🇴', dial: '+47', name: 'Norway' },
    { code: 'OM', flag: '🇴🇲', dial: '+968', name: 'Oman' },
    { code: 'PK', flag: '🇵🇰', dial: '+92', name: 'Pakistan' },
    { code: 'PS', flag: '🇵🇸', dial: '+970', name: 'Palestine' },
    { code: 'PA', flag: '🇵🇦', dial: '+507', name: 'Panama' },
    { code: 'PY', flag: '🇵🇾', dial: '+595', name: 'Paraguay' },
    { code: 'PE', flag: '🇵🇪', dial: '+51', name: 'Peru' },
    { code: 'PH', flag: '🇵🇭', dial: '+63', name: 'Philippines' },
    { code: 'PL', flag: '🇵🇱', dial: '+48', name: 'Poland' },
    { code: 'PT', flag: '🇵🇹', dial: '+351', name: 'Portugal' },
    { code: 'QA', flag: '🇶🇦', dial: '+974', name: 'Qatar' },
    { code: 'RO', flag: '🇷🇴', dial: '+40', name: 'Romania' },
    { code: 'RU', flag: '🇷🇺', dial: '+7', name: 'Russia' },
    { code: 'RW', flag: '🇷🇼', dial: '+250', name: 'Rwanda' },
    { code: 'SA', flag: '🇸🇦', dial: '+966', name: 'Saudi Arabia' },
    { code: 'SN', flag: '🇸🇳', dial: '+221', name: 'Senegal' },
    { code: 'RS', flag: '🇷🇸', dial: '+381', name: 'Serbia' },
    { code: 'SC', flag: '🇸🇨', dial: '+248', name: 'Seychelles' },
    { code: 'SL', flag: '🇸🇱', dial: '+232', name: 'Sierra Leone' },
    { code: 'SG', flag: '🇸🇬', dial: '+65', name: 'Singapore' },
    { code: 'SK', flag: '🇸🇰', dial: '+421', name: 'Slovakia' },
    { code: 'SI', flag: '🇸🇮', dial: '+386', name: 'Slovenia' },
    { code: 'SO', flag: '🇸🇴', dial: '+252', name: 'Somalia' },
    { code: 'ZA', flag: '🇿🇦', dial: '+27', name: 'South Africa' },
    { code: 'KR', flag: '🇰🇷', dial: '+82', name: 'South Korea' },
    { code: 'ES', flag: '🇪🇸', dial: '+34', name: 'Spain' },
    { code: 'LK', flag: '🇱🇰', dial: '+94', name: 'Sri Lanka' },
    { code: 'SD', flag: '🇸🇩', dial: '+249', name: 'Sudan' },
    { code: 'SR', flag: '🇸🇷', dial: '+597', name: 'Suriname' },
    { code: 'SE', flag: '🇸🇪', dial: '+46', name: 'Sweden' },
    { code: 'CH', flag: '🇨🇭', dial: '+41', name: 'Switzerland' },
    { code: 'SY', flag: '🇸🇾', dial: '+963', name: 'Syria' },
    { code: 'TW', flag: '🇹🇼', dial: '+886', name: 'Taiwan' },
    { code: 'TJ', flag: '🇹🇯', dial: '+992', name: 'Tajikistan' },
    { code: 'TZ', flag: '🇹🇿', dial: '+255', name: 'Tanzania' },
    { code: 'TH', flag: '🇹🇭', dial: '+66', name: 'Thailand' },
    { code: 'TL', flag: '🇹🇱', dial: '+670', name: 'Timor-Leste' },
    { code: 'TG', flag: '🇹🇬', dial: '+228', name: 'Togo' },
    { code: 'TN', flag: '🇹🇳', dial: '+216', name: 'Tunisia' },
    { code: 'TR', flag: '🇹🇷', dial: '+90', name: 'Turkey' },
    { code: 'TM', flag: '🇹🇲', dial: '+993', name: 'Turkmenistan' },
    { code: 'UG', flag: '🇺🇬', dial: '+256', name: 'Uganda' },
    { code: 'UA', flag: '🇺🇦', dial: '+380', name: 'Ukraine' },
    { code: 'AE', flag: '🇦🇪', dial: '+971', name: 'United Arab Emirates' },
    { code: 'GB', flag: '🇬🇧', dial: '+44', name: 'United Kingdom' },
    { code: 'US', flag: '🇺🇸', dial: '+1', name: 'United States' },
    { code: 'UY', flag: '🇺🇾', dial: '+598', name: 'Uruguay' },
    { code: 'UZ', flag: '🇺🇿', dial: '+998', name: 'Uzbekistan' },
    { code: 'VE', flag: '🇻🇪', dial: '+58', name: 'Venezuela' },
    { code: 'VN', flag: '🇻🇳', dial: '+84', name: 'Vietnam' },
    { code: 'YE', flag: '🇾🇪', dial: '+967', name: 'Yemen' },
    { code: 'ZM', flag: '🇿🇲', dial: '+260', name: 'Zambia' },
    { code: 'ZW', flag: '🇿🇼', dial: '+263', name: 'Zimbabwe' },
];

// Re-sort alphabetically by French name or leave as is (mixed EN names here). 
// I will just use this list. It covers most.
COUNTRIES.sort((a, b) => a.name.localeCompare(b.name));
